### ISSUE TITLE
Question about why the critic loss in CQL increases

### ISSUE THREAD

**Issue by IantheChan** [takuseno/d3rlpy-benchmarks#1]
![image](https://user-images.githubusercontent.com/34849576/143812341-33840761-8186-42d3-827f-0cc5a1fe79b3.png)
I notice that in CQL_walker2d-random-v0_1_20210618234356, the critic loss keeps increasing during the last 100 epochs, while it seems quite steady at first. Could you give me a hint on why this happens and how can I tune the parameters to get more steady results? I encountered the same problem when I implement some other algorithms in offline settings.

**Comment by takuseno** [comment]
@IantheChan Hi, thanks for the issue. That is a typical offline RL problem. Please look at the average value scale.
https://github.com/takuseno/d3rlpy-benchmarks/blob/main/reproductions/CQL_walker2d-random-v0_1_20210618234356/value_scale.csv

The issue is that the Q-function is extremely overestimating the returns due to offline training. This won't happen in online training or with sufficient data. In CQL case, we can also solve this by increasing the ratio of the conservative loss.

**Comment by IantheChan** [comment]
Thanks for your timely reply! I check out the critic loss is also extremely large. So it seems that the critic is aware that it overestimates the value but it can not properly decrease it given some numerical issues. Is my understanding correct?

**Comment by takuseno** [comment]
Yes, you're right.
